[previous]
name = "xuanwu-sparse"
rustup_dist_server = "https://mirror.xuanwu.openatom.cn"
rustup_update_root = "https://mirror.xuanwu.openatom.cn/rustup"
cargo_config = "[source.crates-io]\nreplace-with = 'xuanwu-sparse'\n[source.xuanwu]\nregistry = \"https://mirror.xuanwu.openatom.cn/crates.io-index\"\n[source.xuanwu-sparse]\nregistry = \"sparse+https://mirror.xuanwu.openatom.cn/index/\"\n[registries.xuanwu]\nindex = \"https://mirror.xuanwu.openatom.cn/crates.io-index\"\n[net]\ngit-fetch-with-cli = true\n"

[current]
name = "rsproxy-sparse"
rustup_dist_server = "https://rsproxy.cn"
rustup_update_root = "https://rsproxy.cn/rustup"
cargo_config = "[source.crates-io]\nreplace-with = 'rsproxy-sparse'\n[source.rsproxy-sparse]\nregistry = \"sparse+https://rsproxy.cn/index/\"\n[net]\ngit-fetch-with-cli = true\n"
